// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function Amusement():Promise<void>;

export function Drama():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HotSearch(arg1:string):Promise<void>;

export function HotSentence(arg1:string):Promise<void>;

export function HotVideo():Promise<void>;

export function List():Promise<Array<entities.Param>>;

export function Search(arg1:string):Promise<void>;

export function Topic():Promise<void>;

export function Trending():Promise<void>;
