// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Amusement() {
  return window['go']['main']['App']['Amusement']();
}

export function Drama() {
  return window['go']['main']['App']['Drama']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HotSearch() {
  return window['go']['main']['App']['HotSearch']();
}

export function HotSentence(arg1) {
  return window['go']['main']['App']['HotSentence'](arg1);
}

export function HotVideo() {
  return window['go']['main']['App']['HotVideo']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Topic() {
  return window['go']['main']['App']['Topic']();
}

export function Trending() {
  return window['go']['main']['App']['Trending']();
}
