// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {amusement} from '../models';
import {drama} from '../models';
import {hotsearch} from '../models';
import {hotsentence} from '../models';
import {hotvideo} from '../models';
import {entities} from '../models';
import {topic} from '../models';
import {trending} from '../models';

export function Amusement():Promise<amusement.Root>;

export function Drama():Promise<drama.Root>;

export function Greet(arg1:string):Promise<string>;

export function HotSearch():Promise<hotsearch.Root>;

export function HotSentence(arg1:string):Promise<hotsentence.Root>;

export function HotVideo():Promise<hotvideo.Root>;

export function List():Promise<Array<entities.Param>>;

export function Topic():Promise<topic.Root>;

export function Trending():Promise<trending.Root>;
